# Generated by Django 4.1 on 2022-09-22 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('contraseña', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('nacimiento', models.DateField()),
            ],
        ),
    ]
