# Generated by Django 4.1 on 2022-09-22 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_remove_usuario_nacimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarrerasCoderhouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorias', models.CharField(max_length=30)),
                ('cursos', models.CharField(max_length=30)),
                ('duracion', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CursosCoderhouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorias', models.CharField(max_length=30)),
                ('cursos', models.CharField(max_length=30)),
                ('duracion', models.CharField(max_length=30)),
            ],
        ),
    ]
