# Generated by Django 4.1 on 2022-09-22 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0003_carrerascoderhouse_cursoscoderhouse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrerascoderhouse',
            old_name='cursos',
            new_name='carreras',
        ),
    ]
